### ISSUE TITLE
Error 500 / Division by zero (youtube)

### ISSUE THREAD

**Issue by Anturix** [pluja/Parasitter#113]
Moin

I'm getting an Error 500 on some Videos (/watch?v=...)

`[2020-10-15 22:28:32,706] ERROR in app: Exception on /watch [GET]                                       
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app                    
    response = self.full_dispatch_request()                                                             
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request       
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception       
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise                   
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request       
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request            
    return self.view_functions[rule.endpoint](**req.view_args)                                          
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view       
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 500, in watch                                                 
    info['rating'] = str((info['like_count'] / (info['like_count'] + info['dislike_count'])) * 100)[0:4]
ZeroDivisionError: division by zero
`
It looks this is happening with Videos that has 0 Thumbs up/down.

I could solve the Issue with one Video, by giving a Thumbs up in plain yt. After that the Video loaded properly.

**Comment by pluja** [comment]
Oh! Thank you for reporting, working on it rn
