### ISSUE TITLE
"GET /twitter HTTP/1.1" 500

### ISSUE THREAD

**Issue by arankaren** [pluja/Parasitter#153]
### Logs
```
127.0.0.1 - - [15/Nov/2020:17:36:04 -0800] "GET /twitter HTTP/1.1" 500 1955 "-" "Mozilla/5.0 (Windows NT 10.0; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [15/Nov/2020:17:36:28 -0800] "GET /twitter HTTP/1.1" 500 1955 "-" "Mozilla/5.0 (Windows NT 10.0; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [15/Nov/2020:17:39:59 -0800] "GET /twitter HTTP/1.1" 500 1955 "-" "Mozilla/5.0 (Windows NT 10.0; rv:76.0) Gecko/20100101 Firefox/76.0"
```

### My nginx config

```
server {
    gzip on;

    listen 80;
    listen [::]:80;

    # replace hostname.local with your server's name
    server_name yotter.local

    # Logs
    access_log  off;
    error_log off;

    client_header_timeout  3m;
    client_body_timeout    3m;
    send_timeout           3m;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/yotter.sock;
        uwsgi_param SCRIPT_NAME "";
        uwsgi_read_timeout 600;
        uwsgi_param UWSGI_SCHEME $scheme;
    }

    # root /srv/http/yotter/src/app/static;
    # location /static { }

    location ~ (^/videoplayback$|/videoplayback/|/vi/|/a/) {
        add_header Access-Control-Allow-Origin *;
        sendfile on;
        tcp_nopush on;
        aio_write on;
        aio threads=default;
        directio 512;
        proxy_http_version 1.1;
        proxy_pass https://$arg_host;
        proxy_set_header Host $arg_host;
        resolver 208.67.222.222 ipv6=off;
    }

    location /static {
        alias /srv/http/yotter/src/app/static;
        expires 30d;
        sendfile on;
        aio threads=default;
    }
}
```

**Comment by FireMasterK** [comment]
Aren't there more logs than that?

**Comment by pluja** [comment]
That's strange. I can't see what could the issue be, logs are really poor on this...

**Comment by arankaren** [comment]
> That's strange. I can't see what could the issue be, logs are really poor on this...

It was a permission problem for the .json files. I already fixed it. Thanks for your time

`$ tail -F /var/log/uwsgi/yotter.log `

```
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xb80df0 pid: 20854 (default app)
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20854)
spawned uWSGI worker 1 (pid: 20903, cores: 1)
spawned uWSGI worker 2 (pid: 20904, cores: 1)
spawned uWSGI worker 3 (pid: 20905, cores: 1)
spawned uWSGI worker 4 (pid: 20906, cores: 1)
spawned uWSGI worker 5 (pid: 20907, cores: 1)
[pid: 20903|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 906 bytes} [Mon Nov 16 07:45:43 2020] GET /login?next=%2F => generated 219 bytes in 380 msecs (HTTP/1.1 302) 5 headers in 301 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 20907|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 976 bytes} [Mon Nov 16 07:45:44 2020] GET /index => generated 3830 bytes in 505 msecs (HTTP/1.1 200) 4 headers in 212 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[2020-11-16 07:46:00,396] ERROR in app: Exception on /twitter [GET]
Traceback (most recent call last):
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/http/yotter/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/srv/http/yotter/src/app/routes.py", line 107, in twitter
    with open("app/cache/{}".format(cache_file), 'w') as fp:
PermissionError: [Errno 13] Permission denied: 'app/cache/karen_20201116-074600.json'
[pid: 20904|app: 0|req: 1/3] 127.0.0.1 () {48 vars in 1071 bytes} [Mon Nov 16 07:45:54 2020] GET /twitter => generated 1955 bytes in 5732 msecs (HTTP/1.1 500) 4 headers in 305 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...

```
