### ISSUE TITLE
login error 

### ISSUE THREAD

**Issue by tangchaoliziyo** [pluja/Parasitter#172]
**Describe the bug**
[2020-12-24 01:33:55,591] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app/routes.py", line 574, in login
    if user.username == config['admin_user']:
KeyError: 'admin_user'

**Comment by FireMasterK** [comment]
Did you setup the config?

**Comment by pluja** [comment]
You need to setup the config on the [yotter-config.json](https://github.com/ytorg/Yotter/blob/dev-indep/yotter-config.json) file. Line 12 has to be the admin user username.

**Comment by tangchaoliziyo** [comment]
> 您需要在[yotter-config.json](https://github.com/ytorg/Yotter/blob/dev-indep/yotter-config.json)文件上设置配置。第12行必须是管理员用户名。

{
	"serverName": "",
	"nitterInstance": "https://nitter.net/",
	"maxInstanceUsers": 1,
	"serverLocation": "",
	"restrictPublicUsage":true,
	"nginxVideoStream":true,
	"maintenance_mode":false,
	"show_admin_message":false,
	"admin_message_title":"Message from the admin",
	"admin_message":"Message from the admin text"
}
I've solved the problem.thank you
