### ISSUE TITLE
Support for Topic Channels

### ISSUE THREAD

**Issue by FireMasterK** [pluja/Parasitter#176]
**Describe the bug**
Topic Channels are broken.

**To Reproduce**
https://yotter.xyz/channel/UCm1rHFAOS5i_McuG8tIhTYA

**Logs**
```
2021-01-03 06:49:34,062] ERROR in app: Exception on /channel/UCm1rHFAOS5i_McuG8tIhTYA [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 433, in channel
    data = ytch.get_channel_tab_info(id, page, sort)
  File "/usr/src/app/youtube/channel.py", line 123, in get_channel_tab_info
    content = util.fetch_url(url,
  File "/usr/src/app/youtube/util.py", line 178, in fetch_url
    raise FetchError(str(response.status), reason=response.reason, ip=None)
youtube.util.FetchError: HTTP error during request: 500 Internal Server Error
```

**Additional context**
Topic channels are automatically generated channels by YouTube.

**Comment by LivingWithHippos** [comment]
Getting almost (404 in logs, 500 in the browser) the same error in "normal" channels. I noticed that my instance routes them to /c/ and not to /channel/ but if I manually navigate to the /channel/ version I get the same error.

```shell
ERROR in app: Exception on /c/UCXKNiazqmuUi9CeX_kyDpjw [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 432, in channel
    data = ytch.get_channel_tab_info(id, page, sort)
  File "/usr/src/app/youtube/channel.py", line 123, in get_channel_tab_info
    content = util.fetch_url(url,
  File "/usr/src/app/youtube/util.py", line 178, in fetch_url
    raise FetchError(str(response.status), reason=response.reason, ip=None)
youtube.util.FetchError: HTTP error during request: 404 Not Found
```

EDIT: maybe I should open another issue? I'm not sure it's related, it's just that the stacktrace was the same

**Comment by FireMasterK** [comment]
I believe it's unrelated as Invidious broke too.

**Comment by pluja** [comment]
@LivingWithHippos yes please, open a different issue for this. Thanks!
