### ISSUE TITLE
Proxied images not loading (500, 502) in self-hosted instance

### ISSUE THREAD

**Issue by addiebarron** [pluja/Parasitter#177]
**Describe the bug**
I'm running a self-hosted instance at yt.addieis.online. All images on Youtube pages currently aren't loading! Network request to the /vi/ etc. endpoints hit either a 500 or a 502 error (I haven't yet nailed down when it's one or the other). There's a Python error on the backend that I can't explain (logs below). I'm using a slightly custom docker build for the yotter image, but the only files I've touched have been favicons. Here's the diff between a fresh ytorg/Yotter clone and my Yotter:

Output of `diff -r ~/yotter-source/Yotter ~/Yotter `
```
Binary files yotter-source/Yotter/app/favicon.png and Yotter/app/favicon.png differ
Only in yotter-source/Yotter/app/static: favicon_io.zip
Only in yotter-source/Yotter/app/static/favicons: android-chrome-192x192.png
Binary files yotter-source/Yotter/app/static/favicons/apple-touch-icon.png and Yotter/app/static/favicons/apple-touch-icon.png differ
Binary files yotter-source/Yotter/app/static/favicons/favicon-16x16.png and Yotter/app/static/favicons/favicon-16x16.png differ
Binary files yotter-source/Yotter/app/static/favicons/favicon-32x32.png and Yotter/app/static/favicons/favicon-32x32.png differ
Binary files yotter-source/Yotter/app/static/favicons/favicon.ico and Yotter/app/static/favicons/favicon.ico differ
diff -r yotter-source/Yotter/docker-compose.yml Yotter/docker-compose.yml
1c1
< version: "3.8"
---
> version: '3.8'
14c14
<       test: ["CMD", "mysqladmin", "ping", "--silent"]
---
>       test: ['CMD', 'mysqladmin', 'ping', '--silent']
19c19
<       - "/var/run/ytproxy:/app/socket/"
---
>       - '/var/run/ytproxy:/app/socket/'
22c22
<     image: ytorg/yotter:latest
---
>     build: .
25c25
<       - "127.0.0.1:5000:5000"
---
>       - '127.0.0.1:5000:5000'
33a34,35
>       - ./app/templates:/usr/src/app/app/templates
>       - ./app/static:/usr/src/app/app/static
diff -r yotter-source/Yotter/Dockerfile Yotter/Dockerfile
2a3
>
8c9
< COPY ./requirements.txt /usr/src/app
---
> COPY ./requirements.txt .
15a17
>
diff -r yotter-source/Yotter/.dockerignore Yotter/.dockerignore
4a5
> **/.DS_Store
Only in yotter-source/Yotter/: .git
diff -r yotter-source/Yotter/requirements.txt Yotter/requirements.txt
24c24
< packaging==20.8
---
> packaging==20.7
30c30
< requests==2.25.1
---
> requests==2.25.0
36c36
< SQLAlchemy==1.3.22
---
> SQLAlchemy==1.3.20
diff -r yotter-source/Yotter/yotter-config.json Yotter/yotter-config.json
2c2
< 	"serverName": "yotter.xyz",
---
> 	"serverName": "yt.addieis.online",
4c4
< 	"maxInstanceUsers": 120,
---
> 	"maxInstanceUsers": 10,
12c12
< 	"admin_user":"admin_username",
---
> 	"admin_user":"addie",
```

NGINX conf:
```
server {
    server_name yt.addieis.online;
    access_log off;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /static/ {
        root /home/yotter/Yotter/app/; # Change this depending on where you clone Yotter
        sendfile on;
        aio threads=default;
    }

    location ~ (^/videoplayback$|/videoplayback/|/vi/|/a/|/ytc/) {
        proxy_pass https://unix:/var/run/ytproxy/http-proxy.sock;
        add_header Access-Control-Allow-Origin *;
        sendfile on;
        tcp_nopush on;
        aio_write on;
        aio threads=default;
        directio 512;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/yt.addieis.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/yt.addieis.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = yt.addieis.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name yt.addieis.online;
    return 404; # managed by Certbot
}
```

Repeated error in `docker-compose logs`:
```
yotter_1   | [2021-01-04 16:20:28,317] ERROR in app: Exception on /ytc/AAUvwnj6qRQVOaHn59lEQ3rAjRQIDmRwdQF6bZRp9pgh=s48-c-k-c0xffffffff-no-rj-mo [GET]
yotter_1   | Traceback (most recent call last):
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
yotter_1   |     response = self.full_dispatch_request()
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
yotter_1   |     rv = self.handle_user_exception(e)
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
yotter_1   |     reraise(exc_type, exc_value, tb)
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
yotter_1   |     raise value
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
yotter_1   |     rv = self.dispatch_request()
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
yotter_1   |     return self.view_functions[rule.endpoint](**req.view_args)
yotter_1   |   File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
yotter_1   |     return func(*args, **kwargs)
yotter_1   |   File "/usr/src/app/app/routes.py", line 261, in u
yotter_1   |     page=int(page)
yotter_1   | ValueError: invalid literal for int() with base 10: 'AAUvwnj6qRQVOaHn59lEQ3rAjRQIDmRwdQF6bZRp9pgh=s48-c-k-c0xffffffff-no-rj-mo'
```

**To Reproduce**
- Create a user on https://yt.addieis.online/
- Navigate to any page with proxied YouTube content (searching YouTube is fastest)

**Expected behavior**
Images are proxied and load as expected.

**Screenshots**
![Screen Shot 2021-01-04 at 12 26 48 PM](https://user-images.githubusercontent.com/11164294/103561891-39f7ec00-4e88-11eb-816a-274516e1b5d6.png)

![Screen Shot 2021-01-04 at 12 27 04 PM](https://user-images.githubusercontent.com/11164294/103561907-3d8b7300-4e88-11eb-8513-3518ff3e521a.png)

**Desktop (please complete the following information):**
 - Debian GNU/Linux 10 (buster)
 - All browsers

**Comment by FireMasterK** [comment]
Can you provide your nginx logs from /var/logs/nginx/error.log?

You likely have a unix socket permissions error. (Can be fixed by running the chown command in the documentation)

For the python error, it's caused by an incorrect nginx configuration that forwards the request to the app instead of the proxy, but I'm not sure how this happens as your nginx configuration appears to be correct.

**Comment by addiebarron** [comment]
Hi thank you so much! I must have missed or accidentally undid the chown step! Still running into the same issue after making the change though, albeit with a different non-permissions-related error:

**Before chown**
```
[crit] 27365#27365: *11085 connect() to unix:/var/run/ytproxy/http-proxy.sock failed (13: Permission denied) while connecting to upstream, client: 173.49.104.117, server: yt.addieis.online, request: "GET /vi/cY9zitJFglc/mqdefault.jpg?host=i4.ytimg.com HTTP/1.1", upstream: "https://unix:/var/run/ytproxy/http-proxy.sock:/vi/cY9zitJFglc/mqdefault.jpg?host=i4.ytimg.com", host: "yt.addieis.online", referrer: "https://yt.addieis.online/youtube"
```

**After chown**
```
[error] 4513#4513: *11224 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 173.49.104.117, server: yt.addieis.online, request: "GET /vi/hWCgUKXsLR0/mqdefault.jpg?host=i1.ytimg.com HTTP/1.1", upstream: "https://unix:/var/run/ytproxy/http-proxy.sock:/vi/hWCgUKXsLR0/mqdefault.jpg?host=i1.ytimg.com", host: "yt.addieis.online", referrer: "https://yt.addieis.online/youtube"
```

I've read that this error can be thrown when an https server is set up on port 80 in nginx, but as you said my configuration looks right. Let me know if you recognize that error.

**Comment by addiebarron** [comment]
Ah, found a stray `s`. Changing from `https` to `http://unix:/var/run/ytproxy/http-proxy.sock` in my nginx conf fixed everything!
