### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by juneflowers** [pluja/Parasitter#20]
Hey I just thought I'd check this project out as getting away from Google/Twitter is something we should all be doing but upon trying to build the image I'm hitting an error.  ran (docker build -t yotter:latest .)

`Step 6/10 : RUN flask db init
 ---> Running in 123c9c18cb0b
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/usr/src/app/app/__init__.py", line 14, in <module>
    from app import routes, models, errors
  File "/usr/src/app/app/routes.py", line 34, in <module>
    REGISTRATIONS = config['registrations']
KeyError: 'registrations'
The command '/bin/sh -c flask db init' returned a non-zero code: 1`

**Comment by pluja** [comment]
I don't really know much about Docker. Maybe @Sn0wed1 can help you as he implemented the Docker file and instructions!

**Comment by pluja** [comment]
Meanwhile, you can use the [Normal installation](https://github.com/pluja/Yotter/blob/dev-indep/README.md#test) instead.

**Comment by Sn0wed1** [comment]
@ducky710 What os are you running?

**Comment by Sn0wed1** [comment]
@pluja I think you fixed this with the this [commit](https://github.com/pluja/Yotter/commit/e66729485e493e2027b5526d9ff060ded89cf4d3).

**Comment by juneflowers** [comment]
I'm running Ubuntu 20.04 on docker 19.03.8. Going to trying to build again now

**Comment by juneflowers** [comment]
Can confirm it built this time haha.

![Terminus_cvKlYBFS7b](https://user-images.githubusercontent.com/63337938/92269625-8d463780-eeb2-11ea-8fa5-0c3362a72353.jpg)

**Comment by juneflowers** [comment]
It's up and working. I wasn't sure if I should open a whole new issue for this since it's so small but it looks like maybe you changed names somewhere along the way and missed one.
![firefox_GooQXwX01W](https://user-images.githubusercontent.com/63337938/92271620-23c82800-eeb6-11ea-9d48-8d086f8bb400.jpg)

**Comment by pluja** [comment]
Oops! Fixing it rn!
