### ISSUE TITLE
Error loading Twitter feed

### ISSUE THREAD

**Issue by pluja** [pluja/Parasitter#42]
This needs a quick fix:

```
[2020-09-09 11:09:39,667] ERROR in app: Exception on /twitter [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Yotter/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/Yotter/app/routes.py", line 61, in twitter
    posts.extend(getFeed(followingList))
  File "/home/ubuntu/Yotter/app/routes.py", line 672, in getFeed
    newPost.replyingUser=quote.find('a',  attrs={'class':'username'}).text
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by pluja** [comment]
Temporarily fixed.
