### ISSUE TITLE
Youtube videos fail after some time

### ISSUE THREAD

**Issue by danielfomin96** [pluja/Parasitter#47]
Hello,
this project looks amazing, but I cannot watch youtube videos for some reason.
I installed Yotter with docker-compose and have the most recent version.
I access Yotter through nginx.

I get the following error on Firefox:

VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the media download to fail part-way. 
Object { code: 2, message: "A network error caused the media download to fail part-way." }
video.min.js:12:794

Thank you very much

**Comment by danielfomin96** [comment]
I am not sure whether it is the same problem, but videos do not play at all on Safari iOS 13.6.1

**Comment by FireMasterK** [comment]
Hi, have you tried enabling `nginxVideoStream` in the config?

**Comment by danielfomin96** [comment]
That did not solve the problem unfortunately.
I found out that every 30sec I get a warning in the docker logs:
```
[Warning] Access denied for user 'root'@'localhost' (using password: NO)
```
I don't think that it is relevant but maybe you know better

**Comment by pluja** [comment]
Do you have these lines on your `/etc/nginx/sites-available/yotter` file?

```
location /videoplayback {
       proxy_buffering off;
       resolver 1.1.1.1;
       proxy_pass https://$arg_hostname;
       proxy_set_header Host $arg_hostname;
       add_header Access-Control-Allow-Origin *;
     }
```

**Comment by FireMasterK** [comment]
This might need some more debugging, how long did you have to watch a video for that to happen? What browser were you using?

That warning is irrelevant as it's part of the healthcheck.

**Comment by danielfomin96** [comment]
I added these lines and it did not change anything.
I have now this nginx config:
```
server { 
        listen 0.0.0.0:80; 
        server_tokens off; 
        server_name example.com; 
return 301 https://$server_name$request_uri; # enforce https                                                                                                                                                 
}
server {
listen 443 ssl http2;
server_name example.com;
location / { 
proxy_pass http://127.0.0.1:5000/; 
proxy_set_header X-Forwarded-For $remote_addr;  
proxy_set_header Host $host; 
proxy_http_version 1.1;         # to keep alive 
proxy_set_header Connection ""; # to keep alive
# Disable buffering when the nginx proxy gets very resource heavy upon streaming                                                                                                                                 
proxy_buffering off;
} 
location /videoplayback {
proxy_buffering off;     
resolver 1.1.1.1;  
proxy_pass https://$arg_hostname; 
proxy_set_header Host $arg_hostname;
add_header Access-Control-Allow-Origin *; 
}                                                                                                                                                                                                           
}     
```

I use Firefox 80.0.1 on PC and Safari on iPhoneSE1 13.6.1.
On PC a video runs for about 50sec and on iOS not at all.

**Comment by FireMasterK** [comment]
Interesting, does the request cancel out? You can find this out by opening devtools and going into the network tab. I'm unable to reproduce this issue on my instance.

**Comment by danielfomin96** [comment]
Two streams are loaded and return 200 after 18000ms each

**Comment by FireMasterK** [comment]
Interesting, for me the connection does not close / return a status code, we can probably implement some kind of a retry mechanism then

**Comment by danielfomin96** [comment]
I got the following error on server once 10 minutes ago:
```
ERROR in app: Exception on /stream/https:YotterSlashYotterSlashr3---sn-h0jeln7e.googlevideo.comYotterSlashvideoplayback?expire=1599872728&ei=eMpbX... [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 348, in stream
    req = s.get(url, stream = True)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
But it does not repeat for every failed video

**Comment by FireMasterK** [comment]
You have not set `nginxVideoStream` to be true in the config...
If you have set it, run `docker-compose restart`

**Comment by danielfomin96** [comment]
I am sorry, I must have restarted the container improperly... But now I get the following error:
```
[2020-09-11 19:34:40,697] ERROR in app: Exception on /50x.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 186, in u
    user = getTwitterUserInfo(username)
  File "/usr/src/app/app/routes.py", line 595, in getTwitterUserInfo
    response = urllib.request.urlopen('{instance}{user}'.format(instance=NITTERINSTANCE, user=username)).read()
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
My config is the following:
```
{
        "serverName": "example.site",
        "nitterInstance": "https://nitter.net/",
        "maxInstanceUsers": 30,
        "serverLocation": "Germany",
        "restrictPublicUsage":true,
        "nginxVideoStream":true,
        "maintenance_mode":false,
        "show_admin_message":false,
        "admin_message_title":"Message from the admin",
        "admin_message":"Message from the admin text"
}
```

**Comment by FireMasterK** [comment]
Not sure why that can happen, what twitter page did you visit?

**Comment by danielfomin96** [comment]
Actually non, I was just watching youtube videos on two devices. I do not yet know how to replicate it.

**Comment by danielfomin96** [comment]
So the youtube videos work, thank you very much, it was my error by not correctly restarting the container after changing the config.
Thank you very much.
I think the other error is not related and it does not make problems in the browser (yet..)

**Comment by danielfomin96** [comment]
No sorry, the error is a problem.
The video stopped again

This time the second stream gave the error 500 and I guess no /50x.html file could be found

**Comment by FireMasterK** [comment]
Interesting, can you check your nginx error logs? They should contain some info.

**Comment by danielfomin96** [comment]
```
2020/09/11 21:56:08 [crit] 2821726#2821726: *1 bind(0.0.0.0) failed (22: Invalid argument) while connecting to upstream, client: 111.111.111.111, server: example.com, request: "GET /videoplayback?expire=1599875764&ei=VNZbX9fDMYuUgQeD4onQBg&ip=111.111.111.111&id=o-AP0VwpsFUPjWgY0BFr3QNfhCyoPU11Vi7n4sCd5-5pN1&itag=18&source=youtube&requiressl=yes&mh=b9&mm=31%2C29&mn=sn-h0jeen76%2Csn-h0jeln7e&ms=au%2Crdu&mv=m&mvi=3&pl=26&initcwndbps=1277500&vprv=1&mime=video%2Fmp4&gir=yes&clen=24399764&ratebypass=yes&dur=721.327&lmt=1599698844570040&mt=1599854081&fvip=3&c=WEB&txp=5531422&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJVfX8H6KouCKcw_zfphOhUNc2AATjrB3w2EWkzQyp9DAiEAsSzrCCkbaQDIfGQ6VHQq8tUBeDsHZ8Sfd8QNVIrIF4k%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJdUxAiCmeNJ63rJYUZkDBpzltjQlvDKPvL8t0Bv09q9AiAVFGlYKYLr6A4eVl9f7UXS5O0Pv3L2e9g1Atx7VEu0tg%3D%3D&hostname=r3---sn-h0jeen76.googlevideo.com HTTP/2.0", upstream: "https://:443/videoplayback?expire=1599875764&ei=VNZbX9fDMYuUgQeD4onQBg&ip=111.111.111.111&id=o-AP0VwpsFUPjWgY0BFr3QNfhCyoPU11Vi7n4sCd5-5pN1&itag=18&source=youtube&requiressl=yes&mh=b9&mm=31%2C29&mn=sn-h0jeen76%2Csn-h0jeln7e&ms=au%2Crdu&mv=m&mvi=3&pl=26&initcwndbps=1277500&vprv=1&mime=video%2Fmp4&gir=yes&clen=24399764&ratebypass=yes&dur=721.327&lmt=1599698844570040&mt=1599854081&fvip=3&c=WEB&txp=5531422&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJVfX8H6KouCKcw_zfphOhUNc2AATjrB3w2EWkzQyp9DAiEAsSzrCCkbaQDIfGQ6VHQq8tUBeDsHZ8Sfd8QNVIrIF4k%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJdUxAiCmeNJ63rJYUZkDBpzltjQlvDKPvL8t0Bv09q9AiAVFGlYKYLr6A4eVl9f7UXS5O0Pv3L2e9g1Atx7VEu0tg%3D%3D&hostname=r3---sn-h0jeen76.googlevideo.com", host: "example.com", referrer: "https://example.com/watch?v=WHTjyAaS-9E"   
```

**Comment by FireMasterK** [comment]
`resolver 1.1.1.1 ipv6=off;`
Can you change your resolver line to this?

**Comment by danielfomin96** [comment]
Great, it works!
On both devices!
Thank you

**Comment by FireMasterK** [comment]
Awesome! @pluja how do you think we should handle this? Should we add that to the nginx configuration?

**Comment by pluja** [comment]
Yes, I think maybe we should add it. What are other options?

**Comment by FireMasterK** [comment]
I'm not too sure actually, I don't have an ipv6 network to test unfortunately, it would be nice have ipv6 support tho

**Comment by pluja** [comment]
I also don't have IPv6.... We can look into this for sure. I will open an issue.
